---
# tasks file for jobsearch_remove
- name: close port 8081/tcp in firewalld
  ansible.posix.firewalld:
    port: 8081/tcp
    permanent: true
    state: disabled
    immediate: yes

- name: disable http in firewalld
  ansible.posix.firewalld:
    service: http
    permanent: true
    state: disabled
    immediate: yes
  when: disable_http

- name: Check if compose file exists
  stat:
    path: /opt/jobsearch/podman-compose.yml
  register: compose_file

- name: Stop services with podman-compose
  ansible.builtin.shell: |
    cd "{{home_dir}}/jobsearch"; /usr/local/bin/podman-compose down
  become: yes
  when: compose_file.stat.exists

- name: remove previous docker compose if exists
  ansible.builtin.file:
    path: /home/ansible/jobsearch/podman-compose.yml
    state: absent