#SPDX-License-Identifier: MIT-0
---
# tasks file for jobsearch
- name: create data directory
  ansible.builtin.file:
    path: "{{home_dir}}/jobsearch/www/data"
    state: directory
    mode: '0777'

- name: install sqlite
  ansible.builtin.package:
    name: sqlite.x86_64 
    state: present

- name: Create database file if missing
  command: 'sqlite3 {{home_dir}}/jobsearch/www/data/jobsearch.db ""'
           

- name: Create logs table
  shell: |
        sqlite3 {{home_dir}}/jobsearch/www/data/jobsearch.db "
        CREATE TABLE IF NOT EXISTS logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            date TEXT,
            employer TEXT,
            position TEXT,
            method TEXT,
            contact_person TEXT,
            contact_info TEXT,
            outcome TEXT,
            notes TEXT,
            timestamp TEXT DEFAULT CURRENT_TIMESTAMP
        );
        "
- name: Download a file from GitHub
  get_url:
    url: "https://raw.githubusercontent.com/Anarabbasov/jobsearch/main/podman-compose.yml"
    dest: "{{home_dir}}" 


- name: Replace docker image version
  ansible.builtin.replace:
    path: "{{home_dir}}/podman-compose.yml"
    regexp: 'anarabbasov/jobster:0.0.1'
    replace: "anarabbasov/jobster:{{version_to_deploy}}"

- name: Install python3-pip
  ansible.builtin.dnf:
    name: python3-pip
    state: present

- name: Install podman-compose via pip
  ansible.builtin.pip:
    name: podman-compose
    executable: pip3

- name: Start services with podman-compose
  ansible.builtin.command:
    cmd: podman-compose up -d
    chdir: "{{home_dir}}"
