#SPDX-License-Identifier: MIT-0
---
# tasks file for jobsearch
- name: create data directory
  ansible.builtin.file:
    path: "{{home_dir}}/jobsearch/www/data"
    state: directory
    mode: '0777'
- name: install sqlite
  ansible.builtin.package:
    name: sqlite.x86_64 
    state: present

- name: Create database file if missing
  command: sqlite3 /var/www/html/data/jobsearch.db ""
           

- name: Create logs table
  shell: |
        sqlite3 /var/www/html/data/jobsearch.db "
        CREATE TABLE IF NOT EXISTS logs (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            date TEXT,
            employer TEXT,
            position TEXT,
            method TEXT,
            contact_person TEXT,
            contact_info TEXT,
            outcome TEXT,
            notes TEXT,
            timestamp TEXT DEFAULT CURRENT_TIMESTAMP
        );
        "
  
